# Generated by Django 3.1.12 on 2025-09-30 01:55

import admin_portal.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('specialization', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('qualifications', models.JSONField(default=list)),
                ('licenseNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('address', djongo.models.fields.EmbeddedField(model_container=admin_portal.models.Address, null=True)),
                ('emergency_contact', djongo.models.fields.EmbeddedField(model_container=admin_portal.models.EmergencyContact, null=True)),
                ('schedule', djongo.models.fields.EmbeddedField(model_container=admin_portal.models.ScheduleSettings, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('address', djongo.models.fields.EmbeddedField(model_container=admin_portal.models.Address)),
                ('emergency_contact', djongo.models.fields.EmbeddedField(model_container=admin_portal.models.EmergencyContact)),
                ('insurance', djongo.models.fields.EmbeddedField(blank=True, model_container=admin_portal.models.InsuranceInfo, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateTimeField()),
                ('type', models.CharField(choices=[('consultation', 'Consultation'), ('follow-up', 'Follow-up'), ('procedure', 'Procedure'), ('check-up', 'Check-up')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no-show', 'No-Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='admin_portal.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='admin_portal.patient')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-appointment_datetime'],
            },
        ),
    ]
